#!/bin/bash

DISTDIR="$(pwd)/dist/Raven"
FOLDERS="linux32 linux64"

for folder in $FOLDERS; do
    mv "$DISTDIR/$folder/Raven" "$DISTDIR/$folder/app"
    cp platform/linux/Raven.sh "$DISTDIR/$folder"
done
